In [1]:
import pandas as pd

In [3]:
time = [10, 20, 30, 40]
print(time)
ser = pd.Series(time)
print(ser)

[10, 20, 30, 40]
0    10
1    20
2    30
3    40
dtype: int64


In [4]:
input = [[10, "a", True], [20, "b", False], [30, "c", False], [40, "d", True]]
print(input)

[[10, 'a', True], [20, 'b', False], [30, 'c', False], [40, 'd', True]]


In [6]:
pd.DataFrame(input)

0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [7]:
df = pd.DataFrame(input)

In [10]:
import numpy as np
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.arange(100).shape

(100,)

In [12]:
np.arange(100).reshape((25, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [13]:
np.arange(100).reshape((25, 4)).shape

(25, 4)

In [14]:
np.arange(100).reshape((25, 4)).shape[0]

25

In [15]:
np.arange(100).reshape((25, 4)).shape[1]

4

In [17]:
pd.DataFrame(np.arange(100).reshape((25, 4)))

0   1   2   3
0    0   1   2   3
1    4   5   6   7
2    8   9  10  11
3   12  13  14  15
4   16  17  18  19
5   20  21  22  23
6   24  25  26  27
7   28  29  30  31
8   32  33  34  35
9   36  37  38  39
10  40  41  42  43
11  44  45  46  47
12  48  49  50  51
13  52  53  54  55
14  56  57  58  59
15  60  61  62  63
16  64  65  66  67
17  68  69  70  71
18  72  73  74  75
19  76  77  78  79
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [18]:
df = pd.DataFrame(np.arange(100).reshape((25, 4)))

In [19]:
df.head()

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [20]:
df.head(3)

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [21]:
df.tail()

0   1   2   3
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [22]:
np.arange(6).reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
pd.DataFrame(np.arange(6).reshape((3, 2)))

0  1
0  0  1
1  2  3
2  4  5

In [32]:
# df = pd.DataFrame(np.arange(6).reshape((3, 2)))
# df.index = ["01", "02", "03"]
# df.columns = ["A", "B"]
pd.DataFrame(np.arange(6).reshape((3, 2)), index = ["01", "02", "03"], columns= ["A", "B"])

A  B
01  0  1
02  2  3
03  4  5

In [34]:
df = pd.DataFrame(np.arange(6).reshape((3, 2)), index = ["01", "02", "03"], columns= ["A", "B"])

In [35]:
df["A"]

01    0
02    2
03    4
Name: A, dtype: int32

In [36]:
df["B"]

01    1
02    3
03    5
Name: B, dtype: int32

In [38]:
df.iloc[:, 0]

01    0
02    2
03    4
Name: A, dtype: int32

In [39]:
select = ["A", "B"]
df[select]

A  B
01  0  1
02  2  3
03  4  5

In [40]:
df[:2]

A  B
01  0  1
02  2  3

In [42]:
df.iloc[:2, :]

A  B
01  0  1
02  2  3

In [44]:
df.loc[:, "A"]

01    0
02    2
03    4
Name: A, dtype: int32

In [43]:
df.loc[:, select]

A  B
01  0  1
02  2  3
03  4  5

In [45]:
df.loc[["01", "03"], select]

A  B
01  0  1
03  4  5

In [47]:
pd.read_csv("ES=F.csv", encoding = "utf-8")

Date    Close  Adj Close
0    2019/11/24  3118.25    3118.25
1    2019/11/25  3132.75    3132.75
2    2019/11/26  3143.75    3143.75
3    2019/11/27  3153.75    3153.75
4    2019/11/29      NaN        NaN
..          ...      ...        ...
119   2020/4/17  2869.00    2869.00
120   2020/4/19  2847.50    2847.50
121   2020/4/20  2814.00    2814.00
122   2020/4/21  2736.50    2736.50
123   2020/4/22  2775.00    2775.00

[124 rows x 3 columns]

In [51]:
# df = pd.read_csv("ES=F.csv", encoding = "utf-8")
df = pd.read_excel("ES=F.xlsx", encoding = "utf-8")

In [55]:
df.head()

Date    Close  Adj Close
0 2019-11-24  3118.25    3118.25
1 2019-11-25  3132.75    3132.75
2 2019-11-26  3143.75    3143.75
3 2019-11-27  3153.75    3153.75
4 2019-11-29      NaN        NaN

In [53]:
df.to_excel("testA.xlsx")

In [58]:
df["Close"]>3000

0       True
1       True
2       True
3       True
4      False
       ...  
119    False
120    False
121    False
122    False
123    False
Name: Close, Length: 124, dtype: bool

In [59]:
df[df["Close"]>3000]

Date        Close    Adj Close
0  2019-11-24  3118.250000  3118.250000
1  2019-11-25  3132.750000  3132.750000
2  2019-11-26  3143.750000  3143.750000
3  2019-11-27  3153.750000  3153.750000
5  2019-12-01  3146.750000  3146.750000
..        ...          ...          ...
77 2020-02-27  3110.250000  3110.250000
81 2020-03-03  3065.100098  3065.100098
83 2020-03-05  3114.699951  3114.699951
84 2020-03-06  3015.500000  3015.500000
85 2020-03-08  3015.500000  3015.500000

[80 rows x 3 columns]

In [60]:
df[df["Close"]>3000].shape

(80, 3)

In [66]:
df.query("Close > 3000 and Close < 3100")

Date        Close    Adj Close
7  2019-12-03  3091.000000  3091.000000
81 2020-03-03  3065.100098  3065.100098
84 2020-03-06  3015.500000  3015.500000
85 2020-03-08  3015.500000  3015.500000

In [67]:
df.dtypes

Date         datetime64[ns]
Close               float64
Adj Close           float64
dtype: object

In [69]:
df.iloc[4, 1]

nan

In [70]:
type(df.iloc[4, 1])

numpy.float64

In [71]:
df.iloc[4, 1] == "nan"

False

In [75]:
np.isnan(df.iloc[4, 1])

True

In [76]:
~np.isnan(df.iloc[4, 1])

False

In [77]:
np.isnan(df)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
df[~np.isnan(df.iloc[4, 1])

In [ ]:
# Q1: 輸出 0000-1000 的 list
# Q2: 輸出 沒有nan的excel