In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'0.24.1'

In [3]:
import sklearn
sklearn.__version__

'0.21.3'

In [4]:
credit = pd.read_csv("train.csv")

In [5]:
credit.head()

acqic   bacno    cano    conam  contp  csmcu ecfg  etymd flbmk flg_3dsmk  \
0   6881  113261   38038   513.80      5      0    N      0     N         N   
1      0  134508   45725   465.62      5      0    N      2     N         N   
2   6881   15408  188328   513.80      5      0    N      0     N         N   
3   6716  157159   29967  1016.11      5     62    N      5     N         N   
4   5975  105985   81305   713.66      5     62    N      4     N         N   

   ...  iterm  locdt     loctm  mcc  mchno  ovrlt  scity  stocn stscd    txkey  
0  ...      0     33  172652.0  457  59333      N      0    102     0   516056  
1  ...      0      9  105114.0  451      0      N   5817    102     0     4376  
2  ...      0      6  152458.0  457  59333      N      0    102     0   483434  
3  ...      0      5  172946.0  247  50436      N   3281    102     0  1407164  
4  ...      0      6  182129.0  263  93775      N   5817    102     0  1051004  

[5 rows x 23 columns]

In [6]:
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521787 entries, 0 to 1521786
Data columns (total 23 columns):
acqic        1521787 non-null int64
bacno        1521787 non-null int64
cano         1521787 non-null int64
conam        1521787 non-null float64
contp        1521787 non-null int64
csmcu        1521787 non-null int64
ecfg         1521787 non-null object
etymd        1521787 non-null int64
flbmk        1509206 non-null object
flg_3dsmk    1509206 non-null object
fraud_ind    1521787 non-null int64
hcefg        1521787 non-null int64
insfg        1521787 non-null object
iterm        1521787 non-null int64
locdt        1521787 non-null int64
loctm        1521787 non-null float64
mcc          1521787 non-null int64
mchno        1521787 non-null int64
ovrlt        1521787 non-null object
scity        1521787 non-null int64
stocn        1521787 non-null int64
stscd        1521787 non-null int64
txkey        1521787 non-null int64
dtypes: float64(2), int64(16), object(5)
memory us

In [19]:
credit_data = credit.drop("ecfg", axis=1).drop("ovrlt", axis=1).drop("insfg", axis=1)\
.drop("flbmk", axis=1).drop("flg_3dsmk", axis=1)

In [20]:
credit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521787 entries, 0 to 1521786
Data columns (total 18 columns):
acqic        1521787 non-null int64
bacno        1521787 non-null int64
cano         1521787 non-null int64
conam        1521787 non-null float64
contp        1521787 non-null int64
csmcu        1521787 non-null int64
etymd        1521787 non-null int64
fraud_ind    1521787 non-null int64
hcefg        1521787 non-null int64
iterm        1521787 non-null int64
locdt        1521787 non-null int64
loctm        1521787 non-null float64
mcc          1521787 non-null int64
mchno        1521787 non-null int64
scity        1521787 non-null int64
stocn        1521787 non-null int64
stscd        1521787 non-null int64
txkey        1521787 non-null int64
dtypes: float64(2), int64(16)
memory usage: 209.0 MB


In [22]:
X = credit_data.drop(["fraud_ind"], axis=1)
y = credit_data["fraud_ind"]

In [23]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: fraud_ind, dtype: int64

In [52]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521787 entries, 0 to 1521786
Data columns (total 17 columns):
acqic    1521787 non-null int64
bacno    1521787 non-null int64
cano     1521787 non-null int64
conam    1521787 non-null float64
contp    1521787 non-null int64
csmcu    1521787 non-null int64
etymd    1521787 non-null int64
hcefg    1521787 non-null int64
iterm    1521787 non-null int64
locdt    1521787 non-null int64
loctm    1521787 non-null float64
mcc      1521787 non-null int64
mchno    1521787 non-null int64
scity    1521787 non-null int64
stocn    1521787 non-null int64
stscd    1521787 non-null int64
txkey    1521787 non-null int64
dtypes: float64(2), int64(15)
memory usage: 197.4 MB


處理分類-Start

In [7]:
from sklearn.preprocessing import LabelEncoder

In [9]:
credit["ecfg"].head()

0    N
1    N
2    N
3    N
4    N
Name: ecfg, dtype: object

In [10]:
encoder_ecfg = LabelEncoder()
credit_ecfg = credit["ecfg"]
credit_ecfg_encoded = encoder_ecfg.fit_transform(credit_ecfg)
print(encoder_ecfg.classes_)
print(type(credit_ecfg_encoded))
print(credit_ecfg_encoded)

['N' 'Y']
<class 'numpy.ndarray'>
[0 0 0 ... 1 1 0]


In [13]:
pd_ecfg = pd.DataFrame(credit_ecfg_encoded, columns=['ecfg'])
pd_ecfg.head()

ecfg
0     0
1     0
2     0
3     0
4     0

In [14]:
encoder_ovrlt = LabelEncoder()
credit_ovrlt = credit["ovrlt"]
credit_ovrlt_encoded = encoder_ovrlt.fit_transform(credit_ovrlt)
print(encoder_ovrlt.classes_)
print(type(credit_ovrlt_encoded))
print(credit_ovrlt_encoded)

['N' 'Y']
<class 'numpy.ndarray'>
[0 0 0 ... 0 0 0]


In [15]:
pd_ovrlt = pd.DataFrame(credit_ovrlt_encoded, columns=['ovrlt'])
pd_ovrlt.head()

ovrlt
0      0
1      0
2      0
3      0
4      0

In [16]:
encoder_insfg = LabelEncoder()
credit_insfg  = credit["insfg"]
credit_insfg_encoded = encoder_insfg.fit_transform(credit_ovrlt)
print(encoder_insfg.classes_)
print(type(credit_insfg_encoded))
print(credit_insfg_encoded)

['N' 'Y']
<class 'numpy.ndarray'>
[0 0 0 ... 0 0 0]


In [17]:
pd_insfg = pd.DataFrame(credit_insfg_encoded, columns=['insfg'])
pd_insfg.head()

insfg
0      0
1      0
2      0
3      0
4      0

處理分類-End

連結X跟分類後的屬性-Start

In [25]:
X_temp = pd.concat([X, pd_ecfg], axis=1)
# X_temp = pd.concat([X, pd_ovrlt], axis=1)
# X_temp = pd.concat([X, pd_insfg], axis=1)
# X_temp = pd.concat([X, pd_ecfg, pd_ovrlt, pd_insfg], axis=1)

In [53]:
X_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521787 entries, 0 to 1521786
Data columns (total 18 columns):
acqic    1521787 non-null int64
bacno    1521787 non-null int64
cano     1521787 non-null int64
conam    1521787 non-null float64
contp    1521787 non-null int64
csmcu    1521787 non-null int64
etymd    1521787 non-null int64
hcefg    1521787 non-null int64
iterm    1521787 non-null int64
locdt    1521787 non-null int64
loctm    1521787 non-null float64
mcc      1521787 non-null int64
mchno    1521787 non-null int64
scity    1521787 non-null int64
stocn    1521787 non-null int64
stscd    1521787 non-null int64
txkey    1521787 non-null int64
ecfg     1521787 non-null int32
dtypes: float64(2), int32(1), int64(15)
memory usage: 203.2 MB


連結X跟分類後的屬性-End

In [28]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train = X_temp
# X_train = X
y_train = y

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
import xgboost as xgb
# import lightgbm as lgb
# clf = LogisticRegression(random_state=0, solver='lbfgs',
#                          multi_class='multinomial').fit(X_train, y_train)
clf = RandomForestClassifier().fit(X_train, y_train)
# clf = GradientBoostingClassifier().fit(X_train, y_train)
# clf = AdaBoostClassifier().fit(X_train, y_train)
# clf = xgb.XGBClassifier().fit(X_train, y_train)

C:\Users\lee\AppData\Local\conda\conda\envs\shu\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [30]:
clf.predict(X_train)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
y_train.to_numpy()

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
from sklearn.metrics import f1_score
f1_score(y_train.to_numpy(), clf.predict(X_train), average='micro')

0.9993540488912048

In [34]:
credit_test = pd.read_csv("test.csv")

In [36]:
credit_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421665 entries, 0 to 421664
Data columns (total 22 columns):
acqic        421665 non-null int64
bacno        421665 non-null int64
cano         421665 non-null int64
conam        421665 non-null float64
contp        421665 non-null int64
csmcu        421665 non-null int64
ecfg         421665 non-null object
etymd        421665 non-null int64
flbmk        417950 non-null object
flg_3dsmk    417950 non-null object
hcefg        421665 non-null int64
insfg        421665 non-null object
iterm        421665 non-null int64
locdt        421665 non-null int64
loctm        421665 non-null float64
mcc          421665 non-null int64
mchno        421665 non-null int64
ovrlt        421665 non-null object
scity        421665 non-null int64
stocn        421665 non-null int64
stscd        421665 non-null int64
txkey        421665 non-null int64
dtypes: float64(2), int64(15), object(5)
memory usage: 70.8+ MB


In [37]:
X_test = credit_test.drop("ecfg", axis=1).drop("flbmk", axis=1)\
.drop("flg_3dsmk", axis=1).drop("insfg", axis=1).drop("ovrlt", axis=1)

In [38]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421665 entries, 0 to 421664
Data columns (total 17 columns):
acqic    421665 non-null int64
bacno    421665 non-null int64
cano     421665 non-null int64
conam    421665 non-null float64
contp    421665 non-null int64
csmcu    421665 non-null int64
etymd    421665 non-null int64
hcefg    421665 non-null int64
iterm    421665 non-null int64
locdt    421665 non-null int64
loctm    421665 non-null float64
mcc      421665 non-null int64
mchno    421665 non-null int64
scity    421665 non-null int64
stocn    421665 non-null int64
stscd    421665 non-null int64
txkey    421665 non-null int64
dtypes: float64(2), int64(15)
memory usage: 54.7 MB


test 補上分類的feature-Start

In [39]:
credit_test["ecfg"].head()

0    N
1    N
2    N
3    N
4    N
Name: ecfg, dtype: object

In [40]:
credit_ecfg_encoded_test = encoder_ecfg.transform(credit_test["ecfg"])
pd_ecfg_test = pd.DataFrame(credit_ecfg_encoded_test, columns=['ecfg'])
pd_ecfg_test.head()

ecfg
0     0
1     0
2     0
3     0
4     0

In [54]:
credit_ovrlt_encoded_test = encoder_ovrlt.fit_transform(credit_test["ovrlt"])
pd_ovrlt_test = pd.DataFrame(credit_ovrlt_encoded_test, columns=['ovrlt'])
pd_ovrlt_test.head()

ovrlt
0      0
1      0
2      0
3      0
4      0

In [55]:
credit_insfg_encoded_test = encoder_insfg.fit_transform(credit_test["insfg"])
pd_insfg_test = pd.DataFrame(credit_insfg_encoded_test, columns=['insfg'])
pd_insfg_test.head()

insfg
0      0
1      0
2      0
3      0
4      0

test 補上分類的feature-End

In [41]:
type(X_test)

pandas.core.frame.DataFrame

In [42]:
type(credit_ecfg_encoded_test)

numpy.ndarray

In [43]:
X_temp_test = pd.concat([X_test, pd_ecfg_test], axis=1)
# X_temp_test = pd.concat([X_test, pd_ovrlt_test], axis=1)
# X_temp_test = pd.concat([X_test, pd_insfg_test], axis=1)
# X_temp_test = pd.concat([X_test, pd_ecfg_test, pd_ovrlt_test, pd_insfg_test], axis=1)

In [44]:
X_temp_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421665 entries, 0 to 421664
Data columns (total 18 columns):
acqic    421665 non-null int64
bacno    421665 non-null int64
cano     421665 non-null int64
conam    421665 non-null float64
contp    421665 non-null int64
csmcu    421665 non-null int64
etymd    421665 non-null int64
hcefg    421665 non-null int64
iterm    421665 non-null int64
locdt    421665 non-null int64
loctm    421665 non-null float64
mcc      421665 non-null int64
mchno    421665 non-null int64
scity    421665 non-null int64
stocn    421665 non-null int64
stscd    421665 non-null int64
txkey    421665 non-null int64
ecfg     421665 non-null int32
dtypes: float64(2), int32(1), int64(15)
memory usage: 56.3 MB


In [45]:
y_test = clf.predict(X_temp_test)

In [46]:
y_test.shape

(421665,)

In [47]:
X_test.head()

acqic   bacno    cano  conam  contp  csmcu  etymd  hcefg  iterm  locdt  \
0   6881  163188  116799  513.8      5      0      0      5      0    102   
1   6881  163188  116799  513.8      5      0      0      5      0    102   
2   6881  163188  116799  513.8      5      0      0      5      0    100   
3   6881  163188  116799  513.8      5      0      0      5      0    100   
4   6881  163188  116799  513.8      5      0      0      5      0    102   

      loctm  mcc  mchno  scity  stocn  stscd   txkey  
0  215328.0  457  59360      0    102      0  592489  
1  222007.0  457  59360      0    102      0  592452  
2  170013.0  457  59360      0    102      0  590212  
3  165914.0  457  59360      0    102      0  590209  
4  215311.0  457  59360      0    102      0  592488

In [48]:
pd.DataFrame(y_test).head()

0
0  0
1  0
2  0
3  0
4  0

In [49]:
credit_test_submit = pd.read_csv("submission_test.csv")
type(credit_test_submit["fraud_ind"])

pandas.core.series.Series

In [50]:
type(pd.DataFrame(y_test))

pandas.core.frame.DataFrame

In [51]:
credit_test_submit["fraud_ind"] = pd.DataFrame(y_test)

In [ ]:
credit_test_submit.head()

In [ ]:
credit_test_submit.to_csv("output.csv", index=False)