In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'0.24.1'

In [3]:
import sklearn
sklearn.__version__

'0.21.3'

In [4]:
credit = pd.read_csv("train.csv")

In [5]:
credit.head()

acqic   bacno    cano    conam  contp  csmcu ecfg  etymd flbmk flg_3dsmk  \
0   6881  113261   38038   513.80      5      0    N      0     N         N   
1      0  134508   45725   465.62      5      0    N      2     N         N   
2   6881   15408  188328   513.80      5      0    N      0     N         N   
3   6716  157159   29967  1016.11      5     62    N      5     N         N   
4   5975  105985   81305   713.66      5     62    N      4     N         N   

   ...  iterm  locdt     loctm  mcc  mchno  ovrlt  scity  stocn stscd    txkey  
0  ...      0     33  172652.0  457  59333      N      0    102     0   516056  
1  ...      0      9  105114.0  451      0      N   5817    102     0     4376  
2  ...      0      6  152458.0  457  59333      N      0    102     0   483434  
3  ...      0      5  172946.0  247  50436      N   3281    102     0  1407164  
4  ...      0      6  182129.0  263  93775      N   5817    102     0  1051004  

[5 rows x 23 columns]

In [6]:
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521787 entries, 0 to 1521786
Data columns (total 23 columns):
acqic        1521787 non-null int64
bacno        1521787 non-null int64
cano         1521787 non-null int64
conam        1521787 non-null float64
contp        1521787 non-null int64
csmcu        1521787 non-null int64
ecfg         1521787 non-null object
etymd        1521787 non-null int64
flbmk        1509206 non-null object
flg_3dsmk    1509206 non-null object
fraud_ind    1521787 non-null int64
hcefg        1521787 non-null int64
insfg        1521787 non-null object
iterm        1521787 non-null int64
locdt        1521787 non-null int64
loctm        1521787 non-null float64
mcc          1521787 non-null int64
mchno        1521787 non-null int64
ovrlt        1521787 non-null object
scity        1521787 non-null int64
stocn        1521787 non-null int64
stscd        1521787 non-null int64
txkey        1521787 non-null int64
dtypes: float64(2), int64(16), object(5)
memory us

處理空值-Start

In [7]:
# drop("flbmk", axis=1).drop("flg_3dsmk", axis=1)
# frame = credit.groupby("flbmk")
print(credit["flbmk"].isna().sum())
print(credit["flbmk"].count())
print(credit["flg_3dsmk"].isna().sum())
print(credit["flg_3dsmk"].count())
# groupby()

12581
1509206
12581
1509206


In [8]:
credit.groupby("flbmk").groups

{'N': Int64Index([      0,       1,       2,       3,       4,       5,       6,
                   7,       8,       9,
             ...
             1518236, 1518237, 1518238, 1518239, 1518240, 1518241, 1518242,
             1518243, 1518245, 1518246],
            dtype='int64', length=1504133),
 'Y': Int64Index([    377,    1138,    1568,    1986,    2033,    2597,    2801,
                3014,    3263,    3692,
             ...
             1515580, 1516002, 1516713, 1516922, 1517342, 1517413, 1517479,
             1517513, 1517768, 1517839],
            dtype='int64', length=5073)}

In [9]:
1504133+5073

1509206

In [10]:
import copy

In [11]:
temp = credit.copy()

In [12]:
temp["flbmk"] = temp["flbmk"].fillna("NaN")

In [13]:
temp.groupby("flbmk").groups

{'N': Int64Index([      0,       1,       2,       3,       4,       5,       6,
                   7,       8,       9,
             ...
             1518236, 1518237, 1518238, 1518239, 1518240, 1518241, 1518242,
             1518243, 1518245, 1518246],
            dtype='int64', length=1504133),
 'NaN': Int64Index([   4827,    5906,    7136,    7523,   37299,  539837,  540047,
              540050,  540052,  540055,
             ...
             1521777, 1521778, 1521779, 1521780, 1521781, 1521782, 1521783,
             1521784, 1521785, 1521786],
            dtype='int64', length=12581),
 'Y': Int64Index([    377,    1138,    1568,    1986,    2033,    2597,    2801,
                3014,    3263,    3692,
             ...
             1515580, 1516002, 1516713, 1516922, 1517342, 1517413, 1517479,
             1517513, 1517768, 1517839],
            dtype='int64', length=5073)}

In [14]:
temp["flg_3dsmk"] = temp["flg_3dsmk"].fillna("NaN")
temp.groupby("flg_3dsmk").groups

{'N': Int64Index([      0,       1,       2,       3,       4,       5,       6,
                   7,       8,       9,
             ...
             1518236, 1518237, 1518238, 1518239, 1518240, 1518241, 1518242,
             1518243, 1518245, 1518246],
            dtype='int64', length=1444867),
 'NaN': Int64Index([   4827,    5906,    7136,    7523,   37299,  539837,  540047,
              540050,  540052,  540055,
             ...
             1521777, 1521778, 1521779, 1521780, 1521781, 1521782, 1521783,
             1521784, 1521785, 1521786],
            dtype='int64', length=12581),
 'Y': Int64Index([     48,      71,      79,     118,     132,     147,     157,
                 171,     438,     471,
             ...
             1517935, 1517949, 1517974, 1517995, 1518006, 1518081, 1518083,
             1518096, 1518151, 1518176],
            dtype='int64', length=64339)}

In [15]:
temp.groupby("flbmk").get_group('NaN')["flbmk"].count()

12581

In [16]:
temp.groupby("flbmk").get_group('NaN')["fraud_ind"].sum()

195

In [17]:
credit_data = credit.drop("ecfg", axis=1).drop("ovrlt", axis=1).drop("insfg", axis=1)
# .drop("flbmk", axis=1).drop("flg_3dsmk", axis=1)

In [18]:
credit_data = credit_data.dropna()

In [19]:
credit_data["flbmk"].isna().sum()

0

In [20]:
credit_data = credit_data.drop("flbmk", axis=1).drop("flg_3dsmk", axis=1)

In [21]:
X = credit_data.drop(["fraud_ind"], axis=1)
y = credit_data["fraud_ind"]

處理空值-End

In [22]:
credit_data = credit.drop("ecfg", axis=1).drop("ovrlt", axis=1).drop("insfg", axis=1)\
.drop("flbmk", axis=1).drop("flg_3dsmk", axis=1)

In [23]:
credit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521787 entries, 0 to 1521786
Data columns (total 18 columns):
acqic        1521787 non-null int64
bacno        1521787 non-null int64
cano         1521787 non-null int64
conam        1521787 non-null float64
contp        1521787 non-null int64
csmcu        1521787 non-null int64
etymd        1521787 non-null int64
fraud_ind    1521787 non-null int64
hcefg        1521787 non-null int64
iterm        1521787 non-null int64
locdt        1521787 non-null int64
loctm        1521787 non-null float64
mcc          1521787 non-null int64
mchno        1521787 non-null int64
scity        1521787 non-null int64
stocn        1521787 non-null int64
stscd        1521787 non-null int64
txkey        1521787 non-null int64
dtypes: float64(2), int64(16)
memory usage: 209.0 MB


In [24]:
credit_data.describe()

acqic         bacno          cano         conam         contp  \
count  1.521787e+06  1.521787e+06  1.521787e+06  1.521787e+06  1.521787e+06   
mean   6.008003e+03  8.209027e+04  1.089170e+05  6.547219e+02  4.829368e+00   
std    1.502420e+03  4.736249e+04  6.090363e+04  4.028078e+02  6.513408e-01   
min    0.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    5.982000e+03  4.140300e+04  5.763500e+04  4.370600e+02  5.000000e+00   
50%    6.716000e+03  8.191200e+04  1.097850e+05  5.919000e+02  5.000000e+00   
75%    6.769000e+03  1.230590e+05  1.618760e+05  8.073400e+02  5.000000e+00   
max    6.884000e+03  1.638840e+05  2.133340e+05  7.208770e+03  6.000000e+00   

              csmcu         etymd     fraud_ind         hcefg         iterm  \
count  1.521787e+06  1.521787e+06  1.521787e+06  1.521787e+06  1.521787e+06   
mean   5.383324e+01  4.149114e+00  1.337572e-02  4.749410e+00  4.962784e-02   
std    2.072135e+01  2.394259e+00  1.148774e-01  1.111927e+00  3.652493e-01   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    6.200000e+01  2.000000e+00  0.000000e+00  5.000000e+00  0.000000e+00   
50%    6.200000e+01  4.000000e+00  0.000000e+00  5.000000e+00  0.000000e+00   
75%    6.200000e+01  5.000000e+00  0.000000e+00  5.000000e+00  0.000000e+00   
max    7.500000e+01  1.000000e+01  1.000000e+00  9.000000e+00  8.000000e+00   

              locdt         loctm           mcc         mchno         scity  \
count  1.521787e+06  1.521787e+06  1.521787e+06  1.521787e+06  1.521787e+06   
mean   4.532732e+01  1.463152e+05  2.978089e+02  5.589022e+04  4.755128e+03   
std    2.601889e+01  5.212107e+04  7.796778e+01  3.082297e+04  1.979815e+03   
min    1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    2.300000e+01  1.109310e+05  2.500000e+02  3.377400e+04  3.795000e+03   
50%    4.500000e+01  1.515220e+05  2.640000e+02  5.936000e+04  5.817000e+03   
75%    6.800000e+01  1.858270e+05  3.430000e+02  7.920000e+04  5.817000e+03   
max    9.000000e+01  2.359590e+05  4.590000e+02  1.033070e+05  6.671000e+03   

              stocn         stscd         txkey  
count  1.521787e+06  1.521787e+06  1.521787e+06  
mean   9.565116e+01  2.485499e-02  9.711265e+05  
std    1.890027e+01  2.216804e-01  5.641322e+05  
min    0.000000e+00  0.000000e+00  0.000000e+00  
25%    1.020000e+02  0.000000e+00  4.869475e+05  
50%    1.020000e+02  0.000000e+00  9.795800e+05  
75%    1.020000e+02  0.000000e+00  1.455200e+06  
max    1.070000e+02  4.000000e+00  1.958239e+06

In [25]:
X = credit_data.drop(["fraud_ind"], axis=1)
y = credit_data["fraud_ind"]

In [26]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: fraud_ind, dtype: int64

In [27]:
X.head()

acqic   bacno    cano    conam  contp  csmcu  etymd  hcefg  iterm  locdt  \
0   6881  113261   38038   513.80      5      0      0      5      0     33   
1      0  134508   45725   465.62      5      0      2      0      0      9   
2   6881   15408  188328   513.80      5      0      0      5      0      6   
3   6716  157159   29967  1016.11      5     62      5      5      0      5   
4   5975  105985   81305   713.66      5     62      4      5      0      6   

      loctm  mcc  mchno  scity  stocn  stscd    txkey  
0  172652.0  457  59333      0    102      0   516056  
1  105114.0  451      0   5817    102      0     4376  
2  152458.0  457  59333      0    102      0   483434  
3  172946.0  247  50436   3281    102      0  1407164  
4  182129.0  263  93775   5817    102      0  1051004

處理分類-Start

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
credit["ecfg"].head()

0    N
1    N
2    N
3    N
4    N
Name: ecfg, dtype: object

In [30]:
encoder_ecfg = LabelEncoder()
credit_ecfg = credit["ecfg"]
credit_ecfg_encoded = encoder_ecfg.fit_transform(credit_ecfg)
print(encoder_ecfg.classes_)
print(type(credit_ecfg_encoded))
print(credit_ecfg_encoded)

['N' 'Y']
<class 'numpy.ndarray'>
[0 0 0 ... 1 1 0]


In [31]:
pd_ecfg = pd.DataFrame(credit_ecfg_encoded, columns=['ecfg'])
pd_ecfg.head()

ecfg
0     0
1     0
2     0
3     0
4     0

In [32]:
encoder_ovrlt = LabelEncoder()
credit_ovrlt = credit["ovrlt"]
credit_ovrlt_encoded = encoder_ovrlt.fit_transform(credit_ovrlt)
print(encoder_ovrlt.classes_)
print(type(credit_ovrlt_encoded))
print(credit_ovrlt_encoded)

['N' 'Y']
<class 'numpy.ndarray'>
[0 0 0 ... 0 0 0]


In [33]:
pd_ovrlt = pd.DataFrame(credit_ovrlt_encoded, columns=['ovrlt'])
pd_ovrlt.head()

ovrlt
0      0
1      0
2      0
3      0
4      0

In [34]:
encoder_insfg = LabelEncoder()
credit_insfg  = credit["insfg"]
credit_insfg_encoded = encoder_insfg.fit_transform(credit_ovrlt)
print(encoder_insfg.classes_)
print(type(credit_insfg_encoded))
print(credit_insfg_encoded)

['N' 'Y']
<class 'numpy.ndarray'>
[0 0 0 ... 0 0 0]


In [35]:
pd_insfg = pd.DataFrame(credit_insfg_encoded, columns=['insfg'])
pd_insfg.head()

insfg
0      0
1      0
2      0
3      0
4      0

處理分類-End

連結X跟分類後的屬性-Start

In [36]:
# X_temp = pd.concat([X, pd_ecfg], axis=1)
# X_temp = pd.concat([X, pd_ovrlt], axis=1)
# X_temp = pd.concat([X, pd_insfg], axis=1)
X_temp = pd.concat([X, pd_ecfg, pd_ovrlt, pd_insfg], axis=1)

連結X跟分類後的屬性-End

分析類別變數-Start

In [37]:
frame = credit.groupby("ecfg")
frame.groups.get("N")[-1]

1521786

In [38]:
frame = credit.groupby("ecfg")
frame.groups
print("ecfg Y", frame.get_group("Y")["fraud_ind"].sum())
print("ecfg Y", frame.get_group("Y")["fraud_ind"].sum()/ frame.groups.get("Y")[-1])
print("ecfg N", frame.get_group("N")["fraud_ind"].sum())
print("ecfg N", frame.get_group("N")["fraud_ind"].sum()/ frame.groups.get("N")[-1])
frame = credit.groupby("ovrlt")
frame.groups
print("ovrlt Y", frame.get_group("Y")["fraud_ind"].sum())
print("ovrlt Y", frame.get_group("Y")["fraud_ind"].sum()/ frame.groups.get("Y")[-1])
print("ovrlt N", frame.get_group("N")["fraud_ind"].sum())
print("ovrlt N", frame.get_group("N")["fraud_ind"].sum()/ frame.groups.get("N")[-1])
frame = credit.groupby("insfg")
frame.groups
print("insfg Y", frame.get_group("Y")["fraud_ind"].sum())
print("insfg Y", frame.get_group("Y")["fraud_ind"].sum()/ frame.groups.get("Y")[-1])
print("insfg N", frame.get_group("N")["fraud_ind"].sum())
print("insfg N", frame.get_group("N")["fraud_ind"].sum()/ frame.groups.get("N")[-1])

ecfg Y 17493
ecfg Y 0.011495053506244312
ecfg N 2862
ecfg N 0.0018806849320469501
ovrlt Y 635
ovrlt Y 0.0004172835563336087
ovrlt N 19720
ovrlt N 0.012958458022350055
insfg Y 37
insfg Y 2.4313808468959482e-05
insfg N 20318
insfg N 0.01335141734777426


分析類別變數-End

加入新的變數, feature engineering-Start

In [66]:
X_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521787 entries, 0 to 1521786
Data columns (total 20 columns):
acqic    1521787 non-null int64
bacno    1521787 non-null int64
cano     1521787 non-null int64
conam    1521787 non-null float64
contp    1521787 non-null int64
csmcu    1521787 non-null int64
etymd    1521787 non-null int64
hcefg    1521787 non-null int64
iterm    1521787 non-null int64
locdt    1521787 non-null int64
loctm    1521787 non-null float64
mcc      1521787 non-null int64
mchno    1521787 non-null int64
scity    1521787 non-null int64
stocn    1521787 non-null int64
stscd    1521787 non-null int64
txkey    1521787 non-null int64
ecfg     1521787 non-null int32
ovrlt    1521787 non-null int32
insfg    1521787 non-null int32
dtypes: float64(2), int32(3), int64(15)
memory usage: 214.8 MB


In [74]:
w = (X_temp["ecfg"]+X_temp["ovrlt"])>1
w.astype(int)
type(w.astype(int))
new_feature = pd.DataFrame(w.astype(int))

In [75]:
new_feature.head()

0
0  0
1  0
2  0
3  0
4  0

In [76]:
new_feature.columns = ['new1']

In [77]:
new_feature.head()

new1
0     0
1     0
2     0
3     0
4     0

加入新的變數, feature engineering-End

In [39]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train = X_temp
# X_train = X
y_train = y

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
import xgboost as xgb
# import lightgbm as lgb
# clf = LogisticRegression(random_state=0, solver='lbfgs',
#                          multi_class='multinomial').fit(X_train, y_train)
clf = RandomForestClassifier().fit(X_train, y_train)
# clf = GradientBoostingClassifier().fit(X_train, y_train)
# clf = AdaBoostClassifier().fit(X_train, y_train)
# clf = xgb.XGBClassifier().fit(X_train, y_train)

C:\Users\lee\AppData\Local\conda\conda\envs\shu\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [41]:
clf.predict(X_train)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
y_train.to_numpy()

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [43]:
from sklearn.metrics import f1_score
f1_score(y_train.to_numpy(), clf.predict(X_train), average='micro')

0.9993251355150228

In [44]:
# f1_score(y_test.to_numpy(), clf.predict(X_test), average='micro')

In [45]:
credit_test = pd.read_csv("test.csv")

In [46]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521787 entries, 0 to 1521786
Data columns (total 17 columns):
acqic    1521787 non-null int64
bacno    1521787 non-null int64
cano     1521787 non-null int64
conam    1521787 non-null float64
contp    1521787 non-null int64
csmcu    1521787 non-null int64
etymd    1521787 non-null int64
hcefg    1521787 non-null int64
iterm    1521787 non-null int64
locdt    1521787 non-null int64
loctm    1521787 non-null float64
mcc      1521787 non-null int64
mchno    1521787 non-null int64
scity    1521787 non-null int64
stocn    1521787 non-null int64
stscd    1521787 non-null int64
txkey    1521787 non-null int64
dtypes: float64(2), int64(15)
memory usage: 197.4 MB


In [47]:
credit_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421665 entries, 0 to 421664
Data columns (total 22 columns):
acqic        421665 non-null int64
bacno        421665 non-null int64
cano         421665 non-null int64
conam        421665 non-null float64
contp        421665 non-null int64
csmcu        421665 non-null int64
ecfg         421665 non-null object
etymd        421665 non-null int64
flbmk        417950 non-null object
flg_3dsmk    417950 non-null object
hcefg        421665 non-null int64
insfg        421665 non-null object
iterm        421665 non-null int64
locdt        421665 non-null int64
loctm        421665 non-null float64
mcc          421665 non-null int64
mchno        421665 non-null int64
ovrlt        421665 non-null object
scity        421665 non-null int64
stocn        421665 non-null int64
stscd        421665 non-null int64
txkey        421665 non-null int64
dtypes: float64(2), int64(15), object(5)
memory usage: 70.8+ MB


In [48]:
X_test = credit_test.drop("ecfg", axis=1).drop("flbmk", axis=1)\
.drop("flg_3dsmk", axis=1).drop("insfg", axis=1).drop("ovrlt", axis=1)

In [49]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421665 entries, 0 to 421664
Data columns (total 17 columns):
acqic    421665 non-null int64
bacno    421665 non-null int64
cano     421665 non-null int64
conam    421665 non-null float64
contp    421665 non-null int64
csmcu    421665 non-null int64
etymd    421665 non-null int64
hcefg    421665 non-null int64
iterm    421665 non-null int64
locdt    421665 non-null int64
loctm    421665 non-null float64
mcc      421665 non-null int64
mchno    421665 non-null int64
scity    421665 non-null int64
stocn    421665 non-null int64
stscd    421665 non-null int64
txkey    421665 non-null int64
dtypes: float64(2), int64(15)
memory usage: 54.7 MB


test 補上分類的feature-Start

In [50]:
credit_test["ecfg"].head()

0    N
1    N
2    N
3    N
4    N
Name: ecfg, dtype: object

In [51]:
credit_ecfg_encoded_test = encoder_ecfg.transform(credit_test["ecfg"])
pd_ecfg_test = pd.DataFrame(credit_ecfg_encoded_test, columns=['ecfg'])
pd_ecfg_test.head()

ecfg
0     0
1     0
2     0
3     0
4     0

In [52]:
credit_ovrlt_encoded_test = encoder_ovrlt.fit_transform(credit_test["ovrlt"])
pd_ovrlt_test = pd.DataFrame(credit_ovrlt_encoded_test, columns=['ovrlt'])
pd_ovrlt_test.head()

ovrlt
0      0
1      0
2      0
3      0
4      0

In [53]:
credit_insfg_encoded_test = encoder_insfg.fit_transform(credit_test["insfg"])
pd_insfg_test = pd.DataFrame(credit_insfg_encoded_test, columns=['insfg'])
pd_insfg_test.head()

insfg
0      0
1      0
2      0
3      0
4      0

test 補上分類的feature-End

In [54]:
type(X_test)

pandas.core.frame.DataFrame

In [55]:
type(credit_ecfg_encoded_test)

numpy.ndarray

In [56]:
# X_temp_test = pd.concat([X_test, pd_ecfg_test], axis=1)
# X_temp_test = pd.concat([X_test, pd_ovrlt_test], axis=1)
# X_temp_test = pd.concat([X_test, pd_insfg_test], axis=1)
X_temp_test = pd.concat([X_test, pd_ecfg_test, pd_ovrlt_test, pd_insfg_test], axis=1)

In [57]:
y_test = clf.predict(X_temp_test)

In [58]:
y_test.shape

(421665,)

In [59]:
X_test.head()

acqic   bacno    cano  conam  contp  csmcu  etymd  hcefg  iterm  locdt  \
0   6881  163188  116799  513.8      5      0      0      5      0    102   
1   6881  163188  116799  513.8      5      0      0      5      0    102   
2   6881  163188  116799  513.8      5      0      0      5      0    100   
3   6881  163188  116799  513.8      5      0      0      5      0    100   
4   6881  163188  116799  513.8      5      0      0      5      0    102   

      loctm  mcc  mchno  scity  stocn  stscd   txkey  
0  215328.0  457  59360      0    102      0  592489  
1  222007.0  457  59360      0    102      0  592452  
2  170013.0  457  59360      0    102      0  590212  
3  165914.0  457  59360      0    102      0  590209  
4  215311.0  457  59360      0    102      0  592488

In [60]:
pd.DataFrame(y_test).head()

0
0  0
1  0
2  0
3  0
4  0

In [61]:
credit_test_submit = pd.read_csv("submission_test.csv")
type(credit_test_submit["fraud_ind"])

pandas.core.series.Series

In [62]:
type(pd.DataFrame(y_test))

pandas.core.frame.DataFrame

In [63]:
credit_test_submit["fraud_ind"] = pd.DataFrame(y_test)

In [64]:
credit_test_submit.head()

txkey  fraud_ind
0  592489          0
1  592452          0
2  590212          0
3  590209          0
4  592488          0

In [65]:
credit_test_submit.to_csv("output.csv", index=False)